name: Daily Run Script

on:
  schedule:
    - cron: '0 7,8 * * *'  # 在 UTC 时间每天的 7:00 和 8:00 运行 (对应美国东部时间 2:00 和 3:00)

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Copy Python files to home directory
      run: |
        cp download.py ~/
        cp upload.py ~/
        cp run.py ~/

    - name: Run script
      run: python ~/run.py
